{
  "required":[
    {"description":"コードとともにライセンスのコピーとコピーライトの表記を含めてください.",
    "label":"License and copyright notice",
    "tag":"include-copyright"},
    {"description":"コードに対する主な改変内容を明示してください.",
    "label":"State Changes",
    "tag":"document-changes"},
    {"description":"ソフトウェアを配布する際には, ソースコードが利用可能でなければなりません. LGPLもしくはOSL3.0の場合, ライブラリのソースコード(プログラム全体ではなくて良い)が利用可能でなければなりません.",
    "label":"Disclose Source","tag":"disclose-source"},
    {"description":"ネットワーク越しにソフトウェアを操作したユーザーにもそのソフトウェアのソースコードを受け取り権利があります.",
    "label":"Network Use is Distribution",
    "tag":"network-use-disclose"},
    {"description":"ライブラリであればオープンソースでないアプリケーションに対しても使用できる可能性があります.",
    "label":"Library usage",
    "tag":"library-usage"},
    {"description":"ソフトウェアに変更を加えた場合, 元とは違う名前をつけてください.",
    "label":"Rename",
    "tag":"rename"}
  ],
  "permitted":[
    {"description":"そのソフトウェアおよびその改編版は商用で使用してもよいです.",
    "label":"Commercial Use","tag":"commercial-use"},
    {"description":"このソフトウェアを改編してもよいです.",
    "label":"Modification",
    "tag":"modifications"},
    {"description":"このソフトウェアを再配布してもよいです.",
    "label":"Distribution",
    "tag":"distribution"},
    {"description":"ソフトウェアを改編し, 第3者へと配布する際に, 元のライセンスにない二次ライセンスを付与してもよいです.",
    "label":"Sublicensing",
    "tag":"sublicense"},
    {"description":"ソフトウェアを配布せずに使用したり改編したりしてもよいです.",
    "label":"Private Use",
    "tag":"private-use"},
    {"description":"このライセンスには著作者から使用者に対して特許権の使用許可という表現が存在します.",
    "label":"Patent Grant",
    "tag":"patent-grant"}
  ],
  "forbidden":[
    {"description":"全てのライセンスにとって暗黙のことですが, このライセンスには著作者の名前やロゴやトレードマークを使用してはならないことが明示されています.",
    "label":"Use Trademark",
    "tag":"trademark-use"},
    {"description":"ソフトウェアは保証無しで提供され, 著作者やライセンス所持者に対してソフトウェアによって発生した損害に対する責任を求めることはできません.",
    "label":"Hold Liable",
    "tag":"no-liability"},
    {"description":"ソフトウェアを改編し第3者に配布する際に, 元のライセンスに含まれていない二次ライセンスを付与することはできません.",
    "label":"Sublicensing",
    "tag":"no-sublicense"},
    {"description":"このソフトウェアは改変禁止です.",
    "label":"Modification",
    "tag":"modifications"},
    {"description":"このソフトウェアを配布してはいけませんYou may not distribute this software.",
    "label":"Distribution",
    "tag":"distribution"},
    {"description":"ソフトウェアを改編し第3者に配布する際に, 元のライセンスに含まれていない二次ライセンスを付与することはできません.",
    "label":"Sublicensing",
    "tag":"sublicense"}
  ]
}
